### ISSUE TITLE
How to put navbar-fixed!

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/paper-dashboard#2]
1.First you need to add the class “navbar-fixed ” on the tag nav and move your structure outside of the div with class “main-panel” like this:
```html
 <div class="sidebar" data-color="orange" data-image="../assets/img/full-screen-image-3.jpg">
        ....
    </div>

    <nav class="navbar navbar-default navbar-fixed">
        <div class="container-fluid">
            ....
        </div>
    </nav>

    <div class="main-panel">
        <-- .navbar used to be here, but was moved outside of this div -->
        ....
    </div>
```

2. Go to your scss partial ```_navbars.scss``` and add the following properties to your class “.navbar-fixed”:
```css
.navbar-fixed{
    position: fixed;
    z-index: 1032;
    right: 0;
    width: 100%;

    & ~ .main-panel > .content {
      padding-top: 95px;
      min-height: calc(100% - 71px);
    }
}

@media (min-width: 991px){
    .navbar-fixed{
        width:calc(100% - 260px);
    }
}
```

3. Compile your scss with [Koala](http://koala-app.com/) ``` assets/scss/paper-dashboard.scss```
